FilmHub/Controllers/FilmoviController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using FilmHub.Data;
using FilmHub.Models;
using FilmHub.Reports;

namespace FilmHub.Controllers
{
    [Authorize]
    public class FilmoviController : Controller
    {
        BazaDbContext bazaPodataka = new BazaDbContext();
        // GET: Filmovi
        [AllowAnonymous]
        public ActionResult Index()
        {
            ViewBag.Title = "Početna o filmovima";
            return View();
        }

        [AllowAnonymous]
        public ActionResult Trazilica()
        {
            ViewBag.Title = "Pretraži naslove";
            return View();
        }

        [AllowAnonymous]
        public ActionResult Novosti()
        {
            ViewBag.Title = "Novosti";
            return View();
        }
        public ActionResult Favoriti()
        {
            ViewBag.Title = "Favoriti";
            return View();
        }

        [AllowAnonymous]
        public ActionResult Popis(string naziv)
        {
            var filmovi = bazaPodataka.PopisFilmova.AsQueryable();

            if (!String.IsNullOrWhiteSpace(naziv))
            {
                filmovi = filmovi.Where(x => x.Naslov.ToUpper().Contains(naziv.ToUpper()));
            }

            

            var rezultatPretrage = filmovi.ToList();

            if (rezultatPretrage.Count == 0)
            {
                ViewBag.Poruka = "Nema rezultata pretrage.";
            }

            return View(rezultatPretrage);
        }


        [AllowAnonymous]
        public ActionResult Detalji(int? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction("Popis");
            }

            
            Film film = bazaPodataka.PopisFilmova.FirstOrDefault(x => x.Id == id);

            if (film == null)
            {
                return RedirectToAction("Popis");
            }
            return View(film);

        }





        public ActionResult Azuriraj(int? id)
        {
            Film film = null;
            if (!id.HasValue)
            {
                film = new Film();
                ViewBag.Title = "Unos novog filma";
                ViewBag.Novi = true;

            }
            else
            {
                film = bazaPodataka.PopisFilmova.FirstOrDefault(x => x.Id == id);

                if(film == null)
                {
                    return HttpNotFound();
                }
                ViewBag.Title = "Ažuriranje podataka o filmu";
                ViewBag.Novi = false;

            }
            return View(film);

        }

        [HttpPost]
        public ActionResult Azuriraj(Film f)
        {

            if (ModelState.IsValid)
            {
                if (f.Id != 0)
                {
                    bazaPodataka.Entry(f).State = System.Data.Entity.EntityState.Modified;
                }

                else
                {
                    bazaPodataka.PopisFilmova.Add(f);
                }
                bazaPodataka.SaveChanges();
                return RedirectToAction("Popis");
            }
            if(f.Id == 0)
            {
                ViewBag.Title = "Kreiranje filma";
                ViewBag.Novi = true;
            }
            else
            {
                ViewBag.Title = "Ažuriranje podataka o filmu";
                ViewBag.Novi = false;   
            }
            return View(f);
        }

        public ActionResult Brisi(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film f = bazaPodataka.PopisFilmova.FirstOrDefault(x => x.Id == id);

            if (f == null)
            {
                return HttpNotFound();
            }
            return View(f);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Brisi(int id)
        {
            Film f = bazaPodataka.PopisFilmova.FirstOrDefault(x => x.Id == id);
            if (f == null)
            {
                return HttpNotFound();
            }
            bazaPodataka.PopisFilmova.Remove(f);
            bazaPodataka.SaveChanges();
            return View("BrisiStatus");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                bazaPodataka.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FilmHub/Controllers/KosaricaItemsController.cs
using FilmHub.Misc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FilmHub.Models;
using FilmHub.Reports;
using FilmHub.Data;

namespace FilmHub.Controllers
{
    public class KosaricaItemsController : Controller
    {
        BazaDbContext bazaPodataka = new BazaDbContext();


        [AllowAnonymous]
        // GET: KosaricaItems
        public ActionResult Index()
        {
            return View(bazaPodataka.PopisFavorita.ToList());
        }

        [AllowAnonymous]
        public ActionResult DodajUKosaricu(int id)
        {
            Film film = bazaPodataka.PopisFilmova.Find(id);

            if (film == null)
            {
                return HttpNotFound();
            }
            else
            {
                bool filmAlreadyInFavorites = bazaPodataka.PopisFavorita.Any(f => f.Naslov == film.Naslov);

                if (filmAlreadyInFavorites)
                {
                    TempData["Poruka"] = "Film je već u favoritima.";
                }
                else
                {
                    Favoriti favItem = new Favoriti
                    {
                        Id = id,
                        Naslov = film.Naslov,
                        Kategorija = film.Kategorija,
                        Godina = film.Godina
                    };
                    bazaPodataka.PopisFavorita.Add(favItem);
                    bazaPodataka.SaveChanges();
                    TempData["Poruka"] = "Film je uspješno dodan u favorite.";
                }
            }
            return RedirectToAction("Index");
        }



        // GET: KosaricaItems/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Naslov,Kategorija,Godina")] Favoriti FavIt)
        {
            if (ModelState.IsValid)
            {
                bazaPodataka.PopisFavorita.Add(FavIt);
                bazaPodataka.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(FavIt);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Favoriti favoriti = bazaPodataka.PopisFavorita.FirstOrDefault(x => x.Id == id);
            if (favoriti == null)
            {
                return HttpNotFound();
            }
            return View(favoriti);
        }

        [AllowAnonymous]
        // GET: KosaricaItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Favoriti FAvIt = bazaPodataka.PopisFavorita.FirstOrDefault(x => x.Id == id);
            if (FAvIt == null)
            {
                return HttpNotFound();
            }
            return View(FAvIt);
        }

        [AllowAnonymous]
        // POST: KosaricaItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Favoriti FAvIt = bazaPodataka.PopisFavorita.FirstOrDefault(x => x.Id == id);
            bazaPodataka.PopisFavorita.Remove(FAvIt);
            bazaPodataka.SaveChanges();
            return View("DeleteStatus");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                bazaPodataka.Dispose();
            }
            base.Dispose(disposing);
        }


        [AllowAnonymous]
        public ActionResult IspisFavorita(string Naslov)
        {
            var f = bazaPodataka.PopisFavorita.ToList();

            if (!String.IsNullOrEmpty(Naslov))
            {
                f = f.Where(x => x.Naslov.ToUpper().Contains(Naslov.ToUpper())).ToList();
            }
            FavoritisReports favoritiReport = new FavoritisReports();
            favoritiReport.ListaFilmovia(f);

            return File(favoritiReport.Podaci, System.Net.Mime.MediaTypeNames.Application.Pdf, "Favorit.pdf");
        }

        [AllowAnonymous]
        public ActionResult ObrisiKosaricu()
        {
            var listaFavorita = bazaPodataka.PopisFavorita.ToList();

            foreach (var f in listaFavorita)
            {
                bazaPodataka.PopisFavorita.Remove(f);
            }

            bazaPodataka.SaveChanges();

            return View("DeleteStatusAll");
        }

    }
}

FilmHub/Views/Filmovi/Azuriraj.cshtml
@using FilmHub.Models
@model Film
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h4>@(ViewBag.Novi ? "Unos novog filma" : $"Ažuriranje podataka o filmu: {Model.Naslov}")</h4>
        </div>
        <div class="card-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "Ispravite podatke!", new { @class = "text-danger" })

                <div class="form-container">
                    @if (!ViewBag.Novi)
                    {
                        <div class="form-group">
                            @Html.LabelFor(model => model.Id, new { @class = "form-label" })
                            <div class="input-disabled">
                                @Html.TextBoxFor(model => model.Id, new { disabled = true, @class = "form-control" })
                            </div>
                        </div>
                    }

                    <div class="form-group">
                        @Html.LabelFor(model => model.Naslov, new { @class = "form-label" })
                        @Html.TextBoxFor(model => model.Naslov, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Naslov, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Produkcija, new { @class = "form-label" })
                        @Html.TextBoxFor(model => model.Produkcija, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Produkcija, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Kategorija, new { @class = "form-label" })
                        @Html.EnumDropDownListFor(model => model.Kategorija, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Kategorija, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Trajanje, new { @class = "form-label" })
                        @Html.TextBoxFor(model => model.Trajanje, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Trajanje, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Godina, new { @class = "form-label" })
                        @Html.TextBoxFor(model => model.Godina, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Godina, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Glumci, new { @class = "form-label" })
                        @Html.TextBoxFor(model => model.Glumci, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Glumci, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Opis, new { @class = "form-label" })
                        @Html.TextAreaFor(model => model.Opis, new { @class = "form-control", rows = 5 })
                        @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
                    </div>

                    <div class="button-group text-center">
                        <input type="submit" value="Spremi" class="btn btn-primary" />
                        @Html.ActionLink("Povratak bez spremanja", "Popis", "Filmovi", null, new { @class = "btn btn-secondary ml-2" })
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<style>
    .form-container {
        padding: 1.5rem;
    }

    .form-group {
        margin-bottom: 1rem;
    }

    .form-label {
        font-weight: 300;
    }

    .input-disabled {
        background-color: #e9ecef;
        padding: 0.375rem 0.75rem;
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
    }

    .button-group {
        margin-top: 1.5rem;
    }

    .ml-2 {
        margin-left: 0.5rem;
    }

    .card-header {
        background-color: #007bff;
        color: #fff;
    }

    .card-body {
        background-color: #f8f9fa;
    }
</style>

FilmHub/Views/Filmovi/Brisi.cshtml
@using FilmHub.Models
@model Film
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Potvrda brisanja</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">

</head>
<body>
    <div class="container mt-4">
        <div class="confirmation-container">
            <h2>Potvrda o brisanju novosti!</h2>
            <p>Jeste li sigurni da želite obrisati "<strong>@Model.Naslov</strong>"?</p>

            @using (Html.BeginForm("Brisi", "Filmovi", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <button type="submit" class="btn btn-danger">Izbriši</button>
                <a href="@Url.Action("Popis", "Filmovi")" class="btn btn-secondary">Odustani</a>
            }
        </div>
    </div>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
</body>
</html>
<style>
    .confirmation-container {
        max-width: 600px;
        margin: 2rem auto;
        padding: 2rem;
        border: 1px solid #dee2e6;
        border-radius: 0.375rem;
        box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);
        background-color: #ffffff;
        text-align: center;
    }

        .confirmation-container h2 {
            margin-bottom: 1.5rem;
            font-size: 1.5rem;
            font-weight: 500;
        }

        .confirmation-container p {
            margin-bottom: 2rem;
            font-size: 1.1rem;
        }

        .confirmation-container .btn {
            margin: 0.5rem;
        }
</style>

FilmHub/Views/Filmovi/BrisiStatus.cshtml
@{
    ViewBag.Title = "BrisiStatus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">

</head>
<body>
    <div class="container mt-4">
        <div class="status-container">
            <h2>Podaci uspješno izbrisani!</h2>
            <a href="@Url.Action("Popis", "Filmovi")" class="btn btn-success">Povratak na popis filmova</a>
        </div>
    </div>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
</body>
</html>
<style>
    .status-container {
        max-width: 600px;
        margin: 2rem auto;
        padding: 2rem;
        border: 1px solid #dee2e6;
        border-radius: 0.375rem;
        box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);
        background-color: #ffffff;
        text-align: center;
    }

        .status-container h2 {
            margin-bottom: 1.5rem;
            font-size: 1.5rem;
            font-weight: 500;
            color: #28a745; /* Zeleni za uspjeh */
        }

        .status-container .btn {
            margin-top: 1rem;
        }
</style>

FilmHub/Views/Filmovi/Detalji.cshtml
@using FilmHub.Models
@model Film
@{
    ViewBag.Title = "Detalji";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">@Model.Naslov</h4>
        </div>
        <div class="card-body">
            <p><strong>Kategorija:</strong> @Model.Kategorija</p>
            <p><strong>Produkcija:</strong> @Model.Produkcija</p>
            <p><strong>Trajanje:</strong> @Model.Trajanje</p>
            <p><strong>Godina:</strong> @Model.Godina</p>
            <p><strong>Glavni glumci:</strong> @Model.Glumci</p>
            <p><strong>Opis:</strong> @Model.Opis</p>
        </div>
        <div class="card-footer text-center">
            <a href="@Url.Action("Popis", "Filmovi")" class="btn btn-primary">Povratak na popis filmova</a>
        </div>
    </div>
</div>

<style>

    .card {
        border-radius: 0.375rem;
        box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.1);
        background-color: #ffffff;
    }

    .card-header {
        background-color: #007bff;
        color: #ffffff;
        padding: 1rem;
        border-bottom: 1px solid #0069d9;
    }

    .card-title {
        margin-bottom: 0;
    }

    .card-body p {
        margin-bottom: 1rem;
        line-height: 1.5;
    }

    .card-footer {
        background-color: #f8f9fa;
        padding: 1rem;
        border-top: 1px solid #dee2e6;
    }

    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }

        .btn-primary:hover {
            background-color: #0056b3;
            border-color: #004085;
        }
</style>

FilmHub/Views/Filmovi/Index.cshtml
@{
    ViewBag.Title = "Početna stranica";
}

<div class="jumbotron text-center">
    <h1 class="display-4">FilmHub</h1>
    <p class="lead">Stanica za besplatno gledanje filmova</p>
    <hr class="my-4">
    <p>Pridružite nam se i uživajte u neograničenom sadržaju.</p>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-4 shadow-sm">
                <div class="card-body">
                    <h2 class="card-title">Pregled filmova</h2>
                    <p class="card-text">Pregled svih filmova na jednom mjestu.</p>
                    <p>@Html.ActionLink("Pregled", "Popis", "Filmovi", null, new { @class = "btn btn-primary" })</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-4 shadow-sm">
                <div class="card-body">
                    <h2 class="card-title">Tražilica</h2>
                    <p class="card-text">Pretraži filmove koji te zanimaju u samo par sekundi.</p>
                    <p>@Html.ActionLink("Pretraži", "Trazilica", "Filmovi", null, new { @class = "btn btn-success" })</p>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .jumbotron {
        background-color: #343a40;
        color: white;
        padding: 2rem 1rem;
        margin-bottom: 2rem;
        border-radius: 0.3rem;
    }

    .card {
        border: none;
        border-radius: 0.5rem;
    }

    .card-body {
        padding: 1.5rem;
    }

    .btn-primary {
        background-color: #007bff;
        border: none;
    }

    .btn-success {
        background-color: #28a745;
        border: none;
    }

    .shadow-sm {
        box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075);
    }

    .my-4 {
        margin: 1.5rem 0;
    }
</style>

FilmHub/Views/Filmovi/Popis.cshtml
@using FilmHub.Models
@model IEnumerable<Film>

@{
    ViewBag.Title = "Popis filmova";
    Layout = "~/Views/Shared/_Layout.cshtml";

    AjaxOptions ajaxOpt = new AjaxOptions()
    {
        UpdateTargetId = "popisFilmova",
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "GET",
        OnBegin = "LoadingRow"
    };
}

<div class="container mt-4">
    <h2 class="mb-4"><strong>Popularni filmovi</strong></h2>

    @if (ViewBag.Poruka != null)
    {
        <div class="alert alert-info">@ViewBag.Poruka</div>
    }
    else
    {
        <div class="film-list">
            @foreach (var film in Model)
            {
                <div class="film-item card mb-4 shadow-sm" onclick="location.href='@Url.Action("Detalji", "Filmovi", new { id = film.Id })'">
                    <div class="card-body">
                        <h3 class="card-title"><strong>@film.Naslov</strong></h3>
                        <br />
                        <p class="card-text"><strong>Produkcija:</strong> @film.Produkcija</p>
                        <p class="card-text"><strong>Kategorija:</strong> @film.Kategorija</p>
                        <p class="card-text"><strong>Trajanje:</strong> @film.Trajanje min</p>
                        <p class="card-text"><strong>Godina:</strong> @film.Godina</p>

                        <div class="button-group @((User.Identity.IsAuthenticated && ((User as FilmHub.Misc.LogiraniKorisnik).IsInRole(FilmHub.Misc.OvlastiKorisnik.Administrator))) ? "admin-buttons" : "non-admin-buttons")">
                            @if (User.Identity.IsAuthenticated && ((User as FilmHub.Misc.LogiraniKorisnik).IsInRole(FilmHub.Misc.OvlastiKorisnik.Administrator)))
                            {
                                @Html.ActionLink("Ažuriraj", "Azuriraj", new { id = film.Id }, new { @class = "btn btn-warning btn-outline" })
                                @Html.ActionLink("Izbriši", "Brisi", new { id = film.Id }, new { @class = "btn btn-danger btn-outline" })
                            }

                            <a href="@Url.Action("DodajUKosaricu", "KosaricaItems", new { id = film.Id })" class="btn btn-heart btn-outline"><i class="fas fa-heart"></i></a>


                        </div>
                    </div>
                </div>
            }
        </div>
    }
</div>

<style>
    .film-list {
        display: flex;
        flex-wrap: wrap;
        gap: 20px;
    }

    .film-item {
        border: none;
        border-radius: 0.5rem;
        box-shadow: 0 4px 10px rgba(0, 0, 0, 0.15); /* Increased shadow for better emphasis */
        box-sizing: border-box;
        transition: transform 0.3s ease, box-shadow 0.3s ease; /* Smooth transitions */
        background: linear-gradient(to bottom right, #ffffff, #f0f0f0); /* Gradient background */
        cursor: pointer;
        width: calc(33.333% - 20px); /* Fixed width for all cards */
    }

        .film-item:hover {
            transform: translateY(-5px); /* Lift the card slightly on hover */
            box-shadow: 0 6px 15px rgba(0, 0, 0, 0.3); /* Increase shadow on hover */
        }

        .film-item .card-body {
            padding: 1.5rem;
        }

    .button-group {
        display: flex;
        gap: 10px;
        margin-top: 10px;
    }

    .admin-buttons {
        justify-content: flex-start;
    }

    .non-admin-buttons {
        justify-content: flex-end;
    }

    .btn {
        display: inline-block;
        padding: 10px 15px;
        text-decoration: none;
        border-radius: 5px;
        text-align: center;
        transition: background-color 0.3s, color 0.3s, border-color 0.3s;
        border: 2px solid transparent;
    }

    .btn-info {
        background-color: #17a2b8;
        border-color: #17a2b8;
        color: white;
    }

    .btn-warning {
        background-color: #ffc107;
        border-color: #ffc107;
        color: white;
    }

    .btn-danger {
        background-color: #dc3545;
        border-color: #dc3545;
        color: white;
    }

    .btn-heart {
        background-color: #ff4d4d; /* Red background */
        color: white;
        border-color: #ff4d4d;
    }

        .btn-heart i {
            margin-right: 0; /* No margin for icon */
        }

    .btn:hover {
        background-color: white;
        color: inherit;
        border-color: currentColor;
    }

    .btn-info:hover {
        color: #17a2b8;
    }

    .btn-warning:hover {
        color: #ffc107;
    }

    .btn-danger:hover {
        color: #dc3545;
    }

    .btn-heart:hover {
        color: #ff4d4d;
    }

    .btn-lg {
        padding: 15px 25px;
        font-size: 1.25rem;
    }

    .btn-outline {
        border: 2px solid currentColor;
    }

    .form-inline .form-group {
        margin-right: 10px;
    }

    .form-inline .form-control {
        width: 300px; /* adjust the width as needed */
        display: inline-block;
    }

    .form-inline .input-group-append {
        position: relative;
        top: -1px;
    }

    .alert {
        margin-top: 20px;
    }
</style>

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet" />

FilmHub/Views/Filmovi/Trazilica.cshtml
@{
    ViewBag.Title = "Pretraži naslove";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FilmHub</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>

        .search-form .form-control {
            border-radius: 0;
            box-shadow: none;
        }

        .search-form .btn {
            border-radius: 0;
            background-color: deepskyblue;
            border-color: deepskyblue;
        }

            .search-form .btn:hover {
                background-color: blue;
                border-color: blue;
            }

            .search-form .btn i {
                margin-right: 0;
            }
    </style>
</head>
<body>
    <h2><strong>@ViewBag.Title</strong></h2>

    <p>Ovdje možete pretraživati naslove filmova.</p>

    @using (Html.BeginForm("Popis", "Filmovi", FormMethod.Get, new { @class = "form-inline mb-4 search-form" }))
    {
        <div class="form-group mr-2">
            <div class="input-group">
                <input type="text" id="naziv" name="naziv" class="form-control" placeholder="Unesi pojam za pretraživanje" aria-label="Unesi pojam za pretraživanje" aria-describedby="search-icon">
                <div class="input-group-append">
                    <button type="submit" class="btn btn-secondary">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    }
</body>
</html>